# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_cxx_compilerclangxx
    - CONFIG=osx_cxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "mUGBuocB+oZOP/BQIQ9x+gvc3kY5QH8Y+8NP+CysbgJTq1n00Q+D9I37RE90WcUIemAiLNcanoQRFCFLjN3isa23uJRbpB4cw7Pr22HgUR+cBq8jeFCim4JdB5DKEv98lA0T/ghYHmVGOB7KGCY5v3mDNCFmpUYuMJMh5gKLQJNzlUvz1KMqhVkCcsFmsS5i8aPoLi/cXs3KuXmeS11w+JF+vj853nQ12puRpZFZOzxDyN+0Hhg9l1xrDfQGzNuWo0HTsvLo1SH/sGWZNh+qc9moVKefONKwqbPc4t+8Ewn2TqTY/FCgOZpKIyjoJolzDeBQEKIF5KhYT/1W21+Ct00Rc8ytWSUOpX6tkQfdp/O3k9T/omOibh9ClKlfCva2Ze0DqcyLCSAs/SWJQd42FoRQW8n7mg7ylWb7lR39t9JP45/3G7W5SyDQSRL4/EUUs6eSFDocfieT33ttJRy+6vJBqPP6avecI3zXKAl4xgEJVvbwz4qBY3ELfOap3soMZZjc6eAsakChN8rhBPSAVY3W/V1LkldONZfpoaejfUUk0pOi/fMJlNdFEjGaCeDlNk5JbPu2sQ2MU/199v6BZHVv7AGFSgXrGGTnL2d2p8ju9y/gE/mMSfY0rWgtHuPxwCBYgkQ5GWoRituZO5KbajfmRFeJOtAq7KQCyk7KiH0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
