appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mUGBuocB+oZOP/BQIQ9x+gvc3kY5QH8Y+8NP+CysbgJTq1n00Q+D9I37RE90WcUIemAiLNcanoQRFCFLjN3isa23uJRbpB4cw7Pr22HgUR+cBq8jeFCim4JdB5DKEv98lA0T/ghYHmVGOB7KGCY5v3mDNCFmpUYuMJMh5gKLQJNzlUvz1KMqhVkCcsFmsS5i8aPoLi/cXs3KuXmeS11w+JF+vj853nQ12puRpZFZOzxDyN+0Hhg9l1xrDfQGzNuWo0HTsvLo1SH/sGWZNh+qc9moVKefONKwqbPc4t+8Ewn2TqTY/FCgOZpKIyjoJolzDeBQEKIF5KhYT/1W21+Ct00Rc8ytWSUOpX6tkQfdp/O3k9T/omOibh9ClKlfCva2Ze0DqcyLCSAs/SWJQd42FoRQW8n7mg7ylWb7lR39t9JP45/3G7W5SyDQSRL4/EUUs6eSFDocfieT33ttJRy+6vJBqPP6avecI3zXKAl4xgEJVvbwz4qBY3ELfOap3soMZZjc6eAsakChN8rhBPSAVY3W/V1LkldONZfpoaejfUUk0pOi/fMJlNdFEjGaCeDlNk5JbPu2sQ2MU/199v6BZHVv7AGFSgXrGGTnL2d2p8ju9y/gE/mMSfY0rWgtHuPxwCBYgkQ5GWoRituZO5KbajfmRFeJOtAq7KQCyk7KiH0=}
